sqlServer: 
    name: ""
    databaseName: ""
    userName: ""
    password: ""
profiseeRunTime:
    adminAccount: ""
    fileRepository:
        userName: ""
        password: ""
        logonType: "NewCredentials"
        location: ""
    #externalDnsUrl: ""
    externalDnsName: ""
    oidc:
        name: "Azure Active Directory"
        authority: ""
        clientId: ""
        clientSecret: ""
        usernameClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
        userIdClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"
        firstNameClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname"
        lastNameClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname"
        emailClaim: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
clusterNode:
    limits:
      cpu: 1
      memory: 4000M
    requests:
      cpu: 1
      memory: 1000M        
image:
    registry: "profisee.azurecr.io"
    repository: "profisee2020r1"
    tag: "latest"
    auth: |
        {
           "auths":{
              "profisee.azurecr.io":{
                 "username":"AUTH_USERNAME",
                 "password":"AUTH_PASSWORD",
                 "email":"AUTH_EMAIL",
                 "auth":"AUTH_AUTH"
              }
           }
        }
licenseFileData: 

oidcFileData: |
    {      
    }
tlsCert: |
    TLSCERT_DATA
tlsKey: |
    TLSKEY_DATA  
    
