{{- if .Values.cloud.azure.useKeyVault -}}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
spec:
    azureIdentity: "akskvidentity"
    selector: azure-pod-identity-binding-selector
{{- end }}

{{- if .Values.cloud.azure.useManagedIdentity -}}
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: {{.Values.cloud.azure.managedIdentity.name }}-binding
spec:
    azureIdentity: {{.Values.cloud.azure.managedIdentity.name }}
    selector: {{.Values.cloud.azure.managedIdentity.name }}
{{- end }}